# setup.py — Auto-generated by GitCraft AI
from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name             = "gitcraft-peo",
    version          = "1.0.0",
    author           = "Tanveer",
    description      = "Auto-generated by GitCraft AI",
    long_description = long_description,
    long_description_content_type = "text/markdown",
    packages         = find_packages(),
    python_requires  = ">=3.9",
    install_requires = ['IPython', 'arxiv', 'faiss', 'fitz', 'fpdf', 'google', 'groq', 'importlib', 'matplotlib', 'modules', 'nbformat', 'networkx', 'nltk', 'numpy', 'pandas', 'plotly', 'pyngrok', 'pyvis', 'requests', 'seaborn'],
    classifiers      = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
